# Generated by Django 5.1.1 on 2024-09-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_users_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
